import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../../styles/Home.module.css";
import axios from "axios";
import Router from "next/router";
import numeral from "numeral";

export default function CollectionDetail() {
  const [cardList, setCardList] = useState([]);
  const [modal, openModal] = useState(false);

  useEffect(() => {
    axios
      .get("/api/v1/card")
      .then(function (response) {
        // handle success
        console.log(response);
        setCardList(response.data.results);
      })
      .catch(function (error) {
        // handle error
        console.log(error);
      })
      .finally(function () {
        // always executed
      });
  }, []);

  const handleModal = () => {
    openModal(!modal);
  };

  const handlePurchaseCard = (id) => {
    axios
      .patch(`/api/v1/card/purchase/${id}`)
      .then(function (response) {
        // handle success
        console.log(response);
        setCardList(response.data.results);
      })
      .catch(function (error) {
        // handle error
        console.log(error);
      })
      .finally(function () {
        Router.push("/");
      });
  };

  return (
    <div>
      <Head>
        <title>Balofy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {cardList &&
          cardList.map((data, index) => {
            return (
              <div
                className={styles.card}
                onClick={() => handlePurchaseCard(data.id)}
              >
                <img
                  className={styles.cardImage}
                  src={data.img}
                  alt="Avatar"
                ></img>
                <div className={styles.container}>
                  <h4>
                    <b>{data.card_name}</b>
                  </h4>
                  <p>Rp. {numeral(data.price).format("0,0")}</p>
                </div>
              </div>
            );
          })}
      </main>

      {modal && (
        // <div className={styles.overlay}>
        //   <div className={styles.popup}>
        //     <h2>Here i am</h2>
        //     <a className={styles.close} href="#">
        //       &times;
        //     </a>
        //     <div className={styles.content}>
        //       Are you sure want to buy this card?
        //     </div>
        //   </div>
        // </div>
        <div className={styles.overlay}>
          <h1>Here</h1>
        </div>
      )}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
